### PR TITLE
Split read cleaning and make updates to data section

### PR DESCRIPTION
**Pull request by yeban**

### CODE REVIEW

**Comment by yannickwurm** [comment]
Sorry I am unable to review. You are correct that this needs to work at 2pm on Friday.

**Comment by yeban** [comment]
Merged the first two commits (data section). 

Leaving the PR open for the last commit (splitting read cleaning into a separate file). I am not confident without review that splitting read cleaning into a separate file won't cause last minute confusion.

**Comment by yeban** [comment]
Will have merge conflicts now - closing

**Comment by yannickwurm** [comment]
read cleaning is friday only for 2h. 
We don't want them to start assembly stuff until monday. Its confusing to have the 2 in the same file (and would make our job on monday harder)

**Comment by yeban** [comment]
Okay. This is sorted:

assembly.md
screen shot 2017-09-28 at 5 57 41 pm

read-cleaning.md
screen shot 2017-09-28 at 9 18 47 pm

**Pull request closed without merging**
